#%RAML 1.0 Trait

headers:
  X-Correlation-Id:
      type: string
      required: false
      description: Identifier for tracking the message across multiple APIs.
      example: 2c1fe860-ab8f-11e8-98d0-529269fb1459